site_name: Rainbow Six PS1 Wiki

theme:
  name: bootstrap386

nav:
  - Home: index.md
  - Operators: operators.md
  - Gear: gear.md
  - Missions: missions.md
  - Terrain: terrain_effects.md
  - Factions: factions.md

