site_name: Rainbow Six PS1 Wiki

theme:
  name: mkdocs  # Use default theme instead of null

extra_css:
  - theme/main.css

nav:
  - Home: index.md
  - Operators: operators.md
  - Gear: gear.md
  - Missions: missions.md
  - Terrain: terrain_effects.md
  - Factions: factions.md

